apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-aspnet-deployment
  namespace: test-aspnet
  labels:
    app: test-aspnet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-aspnet
  template:
    metadata:
      labels:
        app: test-aspnet
    spec:
      containers:
      - name: test-aspnet
        image: ghcr.io/luka-j/argo-test@sha256:972ce7c1228f81499a42a5f7aaa3450de16d3ee1e9cc48405e7ea2b5a67a312e
        imagePullPolicy: Always
        ports:
        - containerPort: 80
