apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-aspnet-deployment
  namespace: test-aspnet
  labels:
    app: test-aspnet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-aspnet
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: test-aspnet
    spec:
      containers:
      - name: test-aspnet
        image: ghcr.io/luka-j/argo-test:sha-151687cbc9b6a3abf7aca610c9a5e97654d56247
        imagePullPolicy: Always
        ports:
        - containerPort: 80
